### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [jt2553/sql-scratch-capstone-turn-in#2]
Criteria 1: Report

    Score Level: 4/4 (Exceeds Expectations)
    Comment(s): Every answer had the three components: 1) SQL queries, 2) output tables as evidence, 3) text interpreting the query results. 

Criteria 2: Query Accuracy

    Score Level: 4/4 (Exceeds Expectations)
    Comment(s): All queries accurately retrieve the data intended. 

Criteria 3: Query Formatting

    Score Level: 4/4 (Exceeds Expectations)
    Comment(s): Queries adhere to the rules of the style guide. Good work using aliases, orderBy and groupBy. The indentations also made the code easy to follow. 

Criteria 4: Understanding underlying concepts and terminology

    Score Level: 4/4 (Exceeds Expectations)
    Comment(s): Report demonstrates an impressive understanding of the dataset. The final conclusion is correct. Great job giving comparisons and commentary in regards to the progression of the data. The user journey table given was also elaborate and had detailed information. Great report.

Overall Score: 16/16

**Comment by jt2553** [comment]
Thank you very much Marvin
